theme: minima

title: "Trenchcoding"
author: "Kevin Johnson"
email: "kevijohn@gmail.com"
description: "Reports from the front lines of development."

timezone: UTC # GitHub uses UTC. This is to force dev environment to match

rss: rss

show_excerpts: true

titles_from_headings:
  strip_title: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other