title: Trenchcoding
author:
  name: kevijohn
  email: kevijohn@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Reports from the front lines of development.

#theme: jekyll-theme-tactile
remote_theme: jekyll/minima

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other