theme: minima

title: "Trenchcoding"
author: "Kevin Johnson"
email: "kevijohn@gmail.com"
description: "Reports from the front lines of development."
url: "https://www.trenchcoding.com"

timezone: UTC # GitHub uses UTC. This is to force dev environment to match
future: false # GitHub Pages will publish future posts if this isn't set to false

rss: rss

show_excerpts: false

# Used by simple links page
social-links:
  LinkedIn:      https://www.linkedin.com/in/kevijohn
  GitHub:        https://github.com/kevijohn

titles_from_headings:
  strip_title: true

header_pages:
  - archive.html

plugins:
  - jekyll-feed
  - jekyll-sitemap

code_block_max_height: 500px

home_post_limit: 5

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: Other