title: "Trenchcoding"
author: "Kevin Johnson"
email: "kevijohn@gmail.com"
description: "Reports from the front lines of development."
  
#theme: jekyll-theme-tactile
theme: "minima"

plugins:
  - jekyll-feed
  - jekyll-sitemap

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other